all:
	g++ -o test1 test1.cpp common.cpp image_patches.cpp recog.cpp  recog_ming.cpp recog_inhand.cpp recog_last.cpp recog_play.cpp `pkg-config --cflags --libs opencv`
	#g++ -o test2 test2.cpp common.cpp image_patches.cpp recog.cpp  recog_ming.cpp recog_inhand.cpp recog_last.cpp recog_play.cpp `pkg-config --cflags --libs opencv`
	#g++ -o card_boundary card_boundary.cpp `pkg-config --cflags --libs opencv`
