all:
	#g++ -o test1 test1.cpp common.cpp image_patches.cpp recog.cpp  recog_ming.cpp recog_inhand.cpp recog_last.cpp recog_play.cpp `pkg-config --cflags --libs opencv`
	#g++ -o online online.cpp common.cpp image_patches.cpp recog.cpp  recog_ming.cpp recog_inhand.cpp recog_last.cpp recog_play.cpp `pkg-config --cflags --libs opencv`
	g++ -o offline offline.cpp common.cpp image_patches.cpp recog.cpp  recog_ming.cpp recog_inhand.cpp recog_last.cpp recog_play.cpp `pkg-config --cflags --libs opencv`
	#g++ -o card_boundary card_boundary.cpp `pkg-config --cflags --libs opencv`
	#g++ -o fetch_image_patch fetch_image_patch.cpp `pkg-config --cflags --libs opencv`
